/**
 * Created by ko3a4ok on 6/25/17.
 */

import I18n from 'react-native-i18n';

I18n.fallbacks = true;

I18n.translations = {
  en: {
    Popular: "Popular",
    Free: "Free",
    Party: "Party",
    Spiritual: "Spiritual",
    "Food and Drinks": "Food and Drinks",
    Play: "Play",
    Art: "Art",
    Business: "Business",
    Movie: "Movie",
    "Education and Development": "Education and Development",
    "Family and kids": "Family and kids",
    Sport:"Sport",
    Hobby: "Hobby",
    Travel: "Travel",
    Other: "Other",

    Events: "Events",
    News: "News",
    "Create Event": "Create Event",
    Categories: "Categories",
    Profile: "Profile",
    Explore: "Explore",
    Settings: "Settings",

    "years ago": "years ago",
    "months ago": "months ago",
    "days ago": "days ago",
    "hours ago": "hours ago",
    "minutes ago": "minutes ago",
    "just now": "just now",

    Search: "Search",

    "Sort by Cost": "Sort by Cost",
    "Sort by Time": "Sort by Time",
    "Sort by Distance": "Sort by Distance",

    Users: "Users",

    From: "From",
    to: "to",
    "Periodic Event": "Periodic Event",
    Every: "Every",
    "Invite friends": "Invite friends",
    "Organized by: ": "Organized by: ",
    Edit: "Edit",
    Leave: "Leave",
    Join: "Join",
    Comments: "Comments",
    "Leave a Comment": "Leave a Comment",
    OK: "OK",
    Cancel: "Cancel",
    "Delete your comment?": "Delete your comment?",
    Start: "Start",
    End: "End",
    Confirm: "Confirm",
    None: "None",
    Address: "Address",
    "Update event": "Update Event",
    Title: "Title",
    Description: "Description",
    "Next event: ": "Next event: ",
    "Start Date": "Start Date",
    "End Date": "End Date",
    Days: "Days",
    "Please set ": "Please set ",
    Price: "Price",
    "Multi Event: ": "Multi Event: ",
    " invited you": " invited you",
    " joined to": " joined to",
    " organized": " organized",
    " started following you": " started following you",

    "Full Name": "Full Name",
    Location: "Location",
    Phone: "Phone",
    Gender: "Gender",
    Birthday: "Birthday",
    "Save Profile": "Save Profile",
    "Edit Profile": "Edit profile",
    " years": " years",
    Followers: "Followers",
    Following: "Following",
    Past: "Past",
    Future: "Future",

    Notifications: "Notifications",
    Messages: "Messages",
    "Upcoming Events": "Upcoming Events",
    "Near Events": "Near Events",
    "Recommended Events": "Recommended Events",
    Privacy: "Privacy",
    "Private Info": "Private Info",
    "Following and Followers": "Following and Followers",
    Logout: "Logout",
    "Only Me": "Only Me",
    "My Followings": "My Followings",
    Anyone: "Anyone",
    Exit: "Exit",
    Login: "Login",
    "Sign In/Up": "Sign In/Up",
    "Login with Facebook": "Login with Facebook",
    "Enter with email": "Enter with email",
    "Confirm Password": "Confirm Password",
    "Passwords are not matched!": "Passwords are not matched!",
    "Name can't be empty!": "Name can't be empty!",
    "Invalid Email!": "Invalid Email!",
    "Password is too short!": "Password is too short!",
    "Sign In": "Sign In",
    "Sign Up": "Sign Up",
    Password: "Password",

    _Weekdays: [
      "Sunday",
      "Monday",
      "Tuesday",
      "Wednesday",
      "Thursday",
      "Friday",
      "Saturday",
    ],
    _Months: [
      "January",
      "February",
      "March",
      "April",
      "May",
      "June",
      "July",
      "August",
      "September",
      "October",
      "November",
      "December",
    ]
},
  uk: {
    Popular: "Популярне",
    Free: "Безкоштовно",
    Party: "Розваги",
    Spiritual: "Духовність",
    "Food and Drinks": "Поїсти та попити",
    Play: "Ігри",
    Art: "Мистецтво",
    Business: "Бізнес",
    Movie: "Кіно",
    "Education and Development": "Навчання та розвиток",
    "Family and kids": "Сім'я та діти",
    Sport:"Спорт",
    Hobby: "Дозвілля",
    Travel: "Подорож",
    Other: "Інше",

    Events: "Події",
    News: "Новини",
    "Create Event": "Створити Подію",
    Categories: "Категорії",
    Profile: "Профіль",
    Explore: "Навколо",
    Settings: "Налаштування",

    "years ago": "років тому",
    "months ago": "місяців тому",
    "days ago": "днів тому",
    "hours ago": "годин тому",
    "minutes ago": "хвилин тому",
    "just now": "щойно",

    Search: "Пошук",

    "Sort by Cost": "Впорядкування за вартістю",
    "Sort by Time": "Впорядкування за часом",
    "Sort by Distance": "Впорядкування за відстанню",

    "Users": "Користувачі",

    "From": "Від",
    "to": "до",
    "Periodic Event": "Періодична подія",
    "Every": "Кожний(а)",
    "Invite friends": "Запросити друзів",
    "Organized by: ": "Організовав(ла)  ",
    Edit: "Редагувати",
    Leave: "Лишити",
    Join: "Приєднатись",
    Comments: "Коментарі",
    "Leave a Comment": "Лишити коментар",
    OK: "Так",
    Cancel: "Відміна",
    "Delete your comment?": "Видалити коментар?",
    Start: "Початок",
    End: "Кінець",
    Confirm: "Підтвердити",
    None: "Нема",
    Address: "Адреса",
    "Update event": "Оновити Подію",
    Title: "Назва",
    Description: "Опис",
    "Next event: ": "Наступна подія: ",
    "Start Date": "Дата початку",
    "End Date": "Дата кінця",
    Days: "Days",
    "Please set ": "Будь-ласка вкажіть ",
    Price: "Ціна",
    "Multi Event: ": "Багаторазова Подія: ",
    " invited you": " запросив(ла) тебе",
    " joined to": " приєднався(лась) до",
    " organized": " організував(ла)",
    " started following you": " Почав(ла) слідкувати за твоїми оновленнями",

    "Full Name": "Повне ім'я",
    Location: "Місце",
    Phone: "Номер телефону",
    Gender: "Стать",
    Birthday: "День народження",
    "Save Profile": "Зберегти",
    "Edit Profile": "Редагувати профайл",
    " years": " років",
    Followers: "Підписники",
    Following: "Підписано",
    Past: "Минуле",
    Future: "Майбутнє",

    Notifications: "Оповіщення",
    Messages: "Повідомлення",
    "Upcoming Events": "Прийдешні події",
    "Near Events": "Події неподалік",
    "Recommended Events": "Рекомендовані події",
    Privacy: "Приватність",
    "Private Info": "Приватна інформація",
    "Following and Followers": "Підписники та друзі",
    Logout: "Залишити",
    "Only Me": "Лише я",
    "My Followings": "Мої друзі",
    Anyone: "Будь-хто",
    Exit: "Вихід",

    Login: "Логін",
    "Sign In/Up": "Увійти/Зареєструватись",
    "Login with Facebook": "Увійти через Facebook",
    "Enter with email": "Увійти через Email",

    "Confirm Password": "Підтвердити пароль",
    "Passwords are not matched!": "Паролі не співпадають!",
    "Name can't be empty!": "Ім'я не може бути порожнім!",
    "Invalid Email!": "Неіснуючий Email!",
    "Password is too short!": "Пароль занадто короткий!",
    "Sign In": "Увійти",
    "Sign Up": "Зареєструватись",
    Password: "Пароль",
    _Weekdays: [
      "Неділя",
      "Понеділок",
      "Вівторок",
      "Середа",
      "Четвер",
      "П'ятниця",
      "Субота",
    ],
    _Months: [
      "Січень",
      "Лютий",
      "Березень",
      "Квітень",
      "Травень",
      "Червень",
      "Липень",
      "Серпень",
      "Вересень",
      "Жовтень",
      "Листопад",
      "Грудень",
    ]
  },
};