# You Podfile should look similar to this file. React Native currently does not support use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
pod 'Firebase'

target 'Tolpa' do
  pod 'React', path: '../node_modules/react-native', :subspecs => [
    'Core',
  ]

  pod 'GoogleMaps'  # <~~ remove this line if you do not want to support GoogleMaps on iOS
  pod 'Firebase/Messaging'
end
